[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.31"

[features]
seeds = false
skip-lint = false

[programs.localnet]
endpoint = "2MV3zaRrgPxFc61FtZxiMa6VA3cGnSV9v9KKL1TFUBJi"
solana-vault = "5seA2qXcGyC9najiKmUVK3u2hfotXZVHtaxuxfrwBLrX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lewis/.config/solana/id.json"

[scripts]
deposit_vault = "yarn run ts-node scripts/05deposit_vault.ts"
init_oapp = "yarn run ts-node scripts/03init_oapp.ts"
oft = "yarn run ts-node scripts/oft.ts"
order_delivery = "yarn run ts-node scripts/set_order_delivery.ts"
print_pda = "yarn run ts-node scripts/00print_pda.ts"
quote_deposit = "yarn run ts-node scripts/quote_oapp.ts"
reinit_oapp = "yarn run ts-node scripts/reinit_oapp_config.ts"
reset_oapp = "yarn run ts-node scripts/reset_oapp_config.ts"
send_oapp = "yarn run ts-node scripts/send.ts"
set_broker = "yarn run ts-node scripts/set_broker.ts"
set_token = "yarn run ts-node scripts/set_token.ts"
setconfig_oapp = "yarn run ts-node scripts/02setconfig_oapp.ts"
setup_oapp = "yarn run ts-node scripts/01setup_oapp.ts"
setup_vault = "yarn run ts-node scripts/04setup_vault.ts"
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
